### ISSUE TITLE
Risk: over-authorization of AWS IoT policy

### ISSUE THREAD

**Issue by P-Verifier** [just4give/parking-lot-monitor-awsiot#1]
We are a security research team and we recently discovered that there is an over-authorization security issue with this project's IoT policy.
The affected file is as following:

	1. parking-lot-monitor-awsiot/device_registration/policy.json

**Comment by just4give** [comment]
@P-Verifier  Oh yeah, you can't be more right. Thanks for calling out. Absolutely not recommended for production with wildcard permissions. This was kept wide open intentionally ( as it's a proof of concept ) so that someone new to AWS can get started without worry about policies at first place. I have added some information in the readme. Please feel free to add more if you feel so.
